### ISSUE TITLE
Back of binary cards showing through on Firefox browsers

### ISSUE THREAD

**Issue by JackMorganNZ** [uccser/cs-field-guide#859]
Issue when displaying flipped cards in Firefox browser:

![image](https://user-images.githubusercontent.com/8001048/52236610-2b1afe80-292c-11e9-8fd4-5adf42d1a841.png)

To solve this issue the following CSS rule needs to added:

```css
.binary-card {
    backface-visibility: hidden;
}
```
